### ISSUE TITLE
Music hackathon

### ISSUE THREAD

**Issue by morgangiraud** [leader-sheep/leadersheep#13]
# 72h de boulot

Je me dis qu'on devrait se faire un "Hackathon" à distance. Ja vois la chose simplement : 
- On fixe une date pour 72h de boulot
- On se met sur un stream tout les deux
- On taff jusqu'à qu'on est produit un son

**Comment by leader-sheep** [comment]
Je pense que 24h c'est un peu plus réaliste si on veut être disponible en même temps et puis je pense que 24h pour créer (et publier) un son même si c'est pourri (et de toute façon faudra pas s'attendre à un truc grandiose au début), c'est amplement suffisant.

Comme je le vois:
- on stream sur Twitch pendant 24h non-stop.
- on commit le résultat sur Github
- on publie sur YouTube ou autre plateformes comme SoundCloud

BOOM.

**Comment by morgangiraud** [comment]
Yo !

On à réussi à en faireu un aujourd'hui ! 5 heures de stream pour cette permière.
[Le fichier du résultat](https://github.com/leader-sheep/leadersheep/tree/master/live-sessions/session1-29-12-2019.rb)
[La chaine twitch](https://www.twitch.tv/leadersheep/) (Le stream à l'air d'être perdu)

Well done!
